disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
identifier_name:
  min_length: 2 # only warning
  excluded: # excluded via string array
    - id
    - URL
    - url
